# Generated by Django 6.0.5 on 2026-05-09 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('telefono', models.CharField(max_length=15)),
                ('ciudad', models.CharField(max_length=100)),
                ('licencia_federal', models.CharField(max_length=50)),
                ('antiguedad', models.IntegerField()),
                ('documentos_vigentes', models.BooleanField(default=True)),
                ('sexo', models.CharField(max_length=20)),
            ],
        ),
    ]
