# Generated by Django 6.0.5 on 2026-05-09 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='sexo',
        ),
        migrations.AddField(
            model_name='registro',
            name='genero',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], default='Masculino', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registro',
            name='licencia_federal',
            field=models.ImageField(upload_to='licencias/'),
        ),
    ]
