# Generated by Django 6.0.5 on 2026-05-10 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_registro_sexo_registro_genero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='estado',
            field=models.CharField(choices=[('Revision', 'En revisión'), ('Aceptado', 'Aceptado'), ('Rechazado', 'Rechazado')], default='Revision', max_length=20),
        ),
    ]
