# Generated by Django 6.0.5 on 2026-05-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_registro_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='alias',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
