# Generated by Django 6.0.5 on 2026-05-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_registro_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='a_imss',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='registro',
            name='afiliacion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='registro',
            name='antiguedad_licencia',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='registro',
            name='asegurado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registro',
            name='b_imss',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='registro',
            name='categoria',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='registro',
            name='colonia',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='registro',
            name='contacto_emergencia',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='registro',
            name='contrato',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='registro',
            name='cp',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='registro',
            name='curp',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='registro',
            name='curso',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='registro',
            name='domicilio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='registro',
            name='empresa',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='registro',
            name='fecha_baja',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registro',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registro',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registro',
            name='gafet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registro',
            name='licencia',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='registro',
            name='lugar_nacimiento',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='registro',
            name='modalidad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='registro',
            name='movimiento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registro',
            name='numero_exp_medico',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='registro',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='registro',
            name='poblacion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='registro',
            name='psicofisico',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='registro',
            name='reingreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registro',
            name='rfc',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='registro',
            name='rol',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='registro',
            name='sindicato',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registro',
            name='socio',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='registro',
            name='unidad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='registro',
            name='vigencia_licencia',
            field=models.DateField(blank=True, null=True),
        ),
    ]
